### ISSUE TITLE
Setup Basic App

### ISSUE THREAD

**Issue by hsprabhakar** [bconklinua/404-group#1]
# **Need to create basic Django backend and React Frontend**

_Note: Everyone is added to this first task_

## **Features**
- [x] Set up Django
- [x] Create several superusers for Django 
- [x] Set up React
- [ ] Create tests if possible
- [ ] Create basic models on Django from UML diagram

**Comment by AGLandberg** [comment]
Created 5 superusers based on our CCIDs and emails. Pull request with info about users: https://github.com/bconklinua/404-group/pull/2
